work_dir: ./work_dir/ntu60/xsub/bone

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: /public/home/zxh_8991/data/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: true

test_feeder_args:
  data_path: /public/home/zxh_8991/data/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: true
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  center: 21
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [7]
batch_size: 128
test_batch_size: 128
num_epoch: 65
nesterov: True
